### ISSUE TITLE
CentOS: Sending signals is prohibited

### ISSUE THREAD

**Issue by wagner-certat** [certtools/intelmq-manager#103]
On CentOS bots can't be stopped due to a permission problem.

Reported as certtools/intelmq#981

I don't know if it's a bug on our side, a configuration issue on the system's side or anything else. And we don't know how to fix it...

**Comment by mf370** [comment]
I managed to make IntelMQ-Manager to work on CentOS. 

I had to change the file ` intelmqctl.py ` and I changed the line 185  ` proc.send_signal(signal.SIGINT) ` to `proc.send_signal(signal.SIGTERM)`, because when the bots are started by IntelMQ-Manager the process doesn't have a `tty`, and when we try to stop them, SIGINT is ignored so they won't stop, while SIGTERM is not ignored, so is possible to stop them..

**Comment by wagner-certat** [comment]
We are getting closer.

SIGTERM is currently not caught by the bot and thus it can't shutdown properly. That can be fixed with `signal.signal(signal.SIGTERM, ...)`.

**Comment by wagner-certat** [comment]
Bugfix is in #1044 for version 1.1
