### ISSUE TITLE
The PyPi wheels contain outdated code

### ISSUE THREAD

**Issue by monoidic** [certtools/intelmq-manager#265]
For some reason, when installing intelmq-manager 3.0.0 via pip, both old and new versions of the code under `intelmq_manager/static` within this repo are present, with the new/correct version being under `${PREFIX}/usr/share/intelmq-manager/html` ([as mentioned in the documentation](https://intelmq.readthedocs.io/en/maintenance/user/intelmq-manager.html#installation-using-pip)), though there is also `${PREFIX}/intelmq_manager/html` for some reason, containing an older version of the same code, from [this](https://github.com/certtools/intelmq-manager/commit/c71b2d6bc31af7c5f670ba81b42a6521ad386796) commit, before the 3.0.0 API change additions.
This likely bloats the size of the wheel, due to code duplication, particularly due to `vis.js` being included twice, and may cause confusion if the upgrade documentation is not thoroughly followed.

**Comment by ghost** [comment]
- Both the wheel and the sdist are affected
- The paths where the source-code resides is affected: `intelmq-manager-3.0.0/intelmq_manager/html/` for the sdist and `intelmq_manager/html/js/` for the wheel
- Not affected are the directories outside: `intelmq-manager-3.0.0/html/` for the sdist and `/usr/share/intelmq_manager/html/` for the wheel
- I assume that this happens when the source 

packaging (the intelmq-manager/api) for pip/pypi is a nightmare. Sticking to rpm/deb would be so much easier...
One "workaround" could be to use a similar approach like `intelmqsetup` for intelmq: A command needs to be called after the installation, which generates the html files and places them at the correct destination.

**Comment by ghost** [comment]
Well. I had an old directory `intelmq_manager/html/` in my local repo (that path is also in the `.gitignore`). Hard to reproduce elsewhere.

**Comment by ghost** [comment]
Maybe the problem was equal to the one which resulted in https://github.com/certtools/intelmq/issues/2116. Apparently `python3 setup.py sdist bdist_wheel` use the code in the `build/` directory and cleaning that one seems to be mandatory.
