### ISSUE TITLE
Saving configuration did'nt work.

### ISSUE THREAD

**Issue by Th4nat0s** [certtools/intelmq-manager#48]
Adding node is not saved.
It's ok for the links.

"Normally" I have a clean installation as described in the installation. .)

**Comment by aaronkaplan** [comment]
On May 24, 2015, at 8:20 AM, Thanat0s <notifications@github.com> wrote:

> Adding node is not saved.
> It's ok for the links.
> 

I can confirm: pipeline.conf gets saved, the rest of the .conf file don't.
Permissions are OK.

I assume this is a regression bug from when everything was moved over to /opt/intelmq.

**Comment by ufoczek** [comment]
at #51 you can find fixed "save.php" file.

**Comment by Th4nat0s** [comment]
Hi ufoczek... i did change the save.php.. it did'nt work better for me.

**Comment by mauroasilva** [comment]
Good afternoon everyone,

It seems like the problem was that a __default__ section was introduced into IntelMQ but the manager wasn't updated to deal with it. For that reason the __default__ was interpreted as just another bot and since bots, right now, can only have letters, numbers, dots and hyphens it is rejected and for that reason it is not saved.

I'll add an exception for the __default__ and i'll also have to figure out exactly how to take the defaults into account. Is it better that the defaults are loaded and shown directly when creating a bot, or should they be added "silently" when the value is not filled?

**Comment by mauroasilva** [comment]
Th4nat0s can you try the new save.php and give me some feedback please.

**Comment by Th4nat0s** [comment]
I do confirm... https://github.com/certtools/intelmq-manager/commit/412412fff481f1ea133b0a50950c2ff21f8c12b9 fix it

**Comment by aaronkaplan** [comment]
On Jun 7, 2015, at 10:07 PM, mauroasilva <notifications@github.com> wrote:

> Good afternoon everyone,
> 
> It seems like the problem was that a default section was introduced into IntelMQ but the manager wasn't updated to deal with it. For that reason the default was interpreted as just another bot and since bots, right now, can only have letters, numbers, dots and hyphens it is rejected and for that reason it is not saved.
> 
> I'll add an exception for the default and i'll also have to figure out exactly how to take the defaults into account. Is it better that the defaults are loaded and shown directly when creating a bot, or should they be added "silently" when the value is not filled?
> 

Tested and seems to work. Thanks.

However, I noticed a small follow-up issue: if you go to the Monitor tab, now you can see the __default__ (status stopped) as if it were a bot. But it's not a bot.
You might want to filter that out from the display table in the Monitor tab.

**Comment by aaronkaplan** [comment]
On Jun 7, 2015, at 10:52 PM, Thanat0s <notifications@github.com> wrote:

> I do confirm... 412412f fix it

Yes, same here. Thanks a lot Mauro!

**Comment by aaronkaplan** [comment]
On Jun 7, 2015, at 10:07 PM, mauroasilva <notifications@github.com> wrote:

> Good afternoon everyone,
> 
> It seems like the problem was that a default section was introduced into IntelMQ but the manager wasn't updated to deal with it. For that reason the default was interpreted as just another bot and since bots, right now, can only have letters, numbers, dots and hyphens it is rejected and for that reason it is not saved.
> 
> I'll add an exception for the default and i'll also have to figure out exactly how to take the defaults into account. Is it better that the defaults are loaded and shown directly when creating a bot, or should they be added "silently" when the value is not filled?
> 

Another thing that I noticed:
now __default__ seems to be treated as a bot.

So, if you do:

% sudo -u intelmq /opt/intelmq/bin/intelmqctl --botnet stop
Stopping Botnet...
__default__ was NOT RUNNING.
...

It things it needs to stop __default__. That's probably not what we want.

**Comment by mauroasilva** [comment]
Yes I know, that is why I said "i'll also have to figure out exactly how to take the defaults into account" because right now it isn't really taking it into account it simply shows it as another bot. I have to figure out exactly how to put it into the user interface...

How should I allow the defaults to be changed?
How should I represent overrides to the defaults vs the defaults themselves?

These are some of the questions I'll have to figure out before putting it into practice.

Regarding intelmqctl that is not an issue of the manager itself but from the intelmqctl that is also not taking into account the defaults.

The feature of the defaults itself is kind of conflictual... should we put system-wide defaults into a separate file? should it be part of an existing configuration file?

**Comment by aaronkaplan** [comment]
On Jun 8, 2015, at 3:03 PM, mauroasilva <notifications@github.com> wrote:

> Yes I know, that is why I said "i'll also have to figure out exactly how to take the defaults into account" because right now it isn't really taking it into account it simply shows it as another bot. I have to figure out exactly how to put it into the user interface...
> 

okay, got it :)
I was just reporting what I found out :)


> How should I allow the defaults to be changed?
Maybe the default should be in a separate file. This way you can easily edit it in a separate tab window ?
Just a suggestion.

> How should I represent overrides to the defaults vs the defaults themselves?
> 
> These are some of the questions I'll have to figure out before putting it into practice.
> 
> Regarding intelmqctl that is not an issue of the manager itself but from the intelmqctl that is also not taking into account the defaults.
> 
yes

> The feature of the defaults itself is kind of conflictual... should we put system-wide defaults into a separate file? should it be part of an existing configuration file?
> 
I'd say yes, in a separate file.
